// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/e77a0d93ef38eabfa04b1072ad3250e2c4d5cfb7/threejs/three.d.ts
declare namespace ReactTHREE {
   export var Renderer;
   export var Scene;
   export var Mesh;
   export var Object3D;
   export var PerspectiveCamera;
   export var render;
}

declare module "react-three" {
    export = ReactTHREE;
}
